# Generated by Django 2.2.8 on 2020-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Is_Candidate',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Is_Organization',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Is_University',
            field=models.BooleanField(null=True),
        ),
    ]
