# Generated by Django 3.0.2 on 2020-03-09 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Address', models.TextField()),
                ('Website', models.URLField()),
                ('Conteact_no', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=50)),
                ('AICTE_college_code', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
