# Generated by Django 3.0.2 on 2020-03-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0011_auto_20200309_1850'),
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('apply_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='Organization.Jobs')),
                ('by_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='University.Profile')),
            ],
        ),
    ]
