# Generated by Django 3.0.2 on 2020-03-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0012_delete_application'),
        ('University', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobenquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('At', models.DateTimeField()),
                ('proposal', models.TextField()),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.Profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Jobs')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
