# Generated by Django 3.0.2 on 2020-05-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='SubDomainMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.PositiveIntegerField(null=True)),
                ('SubDomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain')),
            ],
        ),
        migrations.RemoveField(
            model_name='domainmarks',
            name='Domain_final',
        ),
        migrations.RemoveField(
            model_name='domainmarks',
            name='Name_of_user',
        ),
        migrations.AddField(
            model_name='domainmarks',
            name='Domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='Answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domainanswer',
            name='Answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domainquestion',
            name='Question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='GeneralMarks',
        ),
        migrations.AddField(
            model_name='answer',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
        migrations.AddField(
            model_name='domainanswer',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
        migrations.AddField(
            model_name='domainquestion',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
        migrations.AddField(
            model_name='question',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
    ]
