# Generated by Django 3.0.2 on 2020-05-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='From',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain'),
            preserve_default=False,
        ),
    ]
