# Generated by Django 3.0.2 on 2020-05-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200507_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomainmarks',
            name='SubDomain',
        ),
        migrations.DeleteModel(
            name='DomainMarks',
        ),
        migrations.DeleteModel(
            name='SubDomainMarks',
        ),
    ]
