# Generated by Django 3.0.2 on 2020-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200507_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainquestion',
            name='Level3',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
