# Generated by Django 3.0.2 on 2020-05-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_subdomain_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
        migrations.AddField(
            model_name='domainanswer',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
        migrations.AddField(
            model_name='domainquestion',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
        migrations.AddField(
            model_name='question',
            name='SubDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
    ]
