# Generated by Django 3.0.2 on 2020-05-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200503_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domainanswer',
            name='Answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domainquestion',
            name='Question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_text',
            field=models.TextField(max_length=100),
        ),
    ]
