# Generated by Django 3.0.2 on 2020-08-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customquiz.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_text', models.TextField()),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='customquiz.Domain')),
                ('SubDomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customquiz.SubDomain')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weightage', models.PositiveIntegerField()),
                ('Answer_text', models.TextField()),
                ('Question_related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='customquiz.Question')),
                ('SubDomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customquiz.SubDomain')),
                ('from_Domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_domain', to='customquiz.Domain')),
            ],
        ),
    ]
