# Generated by Django 3.0.2 on 2020-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customquiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='SubDomain',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='from_Domain',
        ),
        migrations.RemoveField(
            model_name='question',
            name='SubDomain',
        ),
        migrations.AddField(
            model_name='question',
            name='primary_key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
