# Generated by Django 3.0.2 on 2020-08-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customquiz', '0002_auto_20200801_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='primary_key',
            new_name='key',
        ),
    ]
