# Generated by Django 3.0.2 on 2020-08-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0017_auto_20200801_0658'),
        ('customquiz', '0003_auto_20200801_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Organization',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Organization.Company'),
            preserve_default=False,
        ),
    ]
