# Generated by Django 3.0.2 on 2020-06-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='blogs')),
                ('Refrences', models.URLField(max_length=255)),
                ('Apply', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('By', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='courses')),
                ('Refrences', models.URLField(max_length=255)),
                ('Apply', models.URLField(max_length=255)),
            ],
        ),
    ]
