# Generated by Django 3.0.2 on 2020-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200629_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Description',
            field=models.TextField(),
        ),
    ]
