# Generated by Django 3.0.2 on 2020-07-09 18:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_domainquestion_level3'),
        ('content', '0004_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 9, 18, 47, 37, 358985, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='Domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='Rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='courses',
            name='Added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 9, 18, 48, 18, 753905, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='Domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='Rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='scheme',
            name='Added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 9, 18, 48, 32, 610691, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='Domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='Rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
