# Generated by Django 3.0.2 on 2020-01-31 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=250)),
                ('Resume', models.FileField(upload_to=None)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill1', models.CharField(max_length=50, null=True)),
                ('Skill2', models.CharField(max_length=50, null=True)),
                ('Skill3', models.CharField(max_length=50, null=True)),
                ('Skill4', models.CharField(max_length=50, null=True)),
                ('fromRecruit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Candidate.Recruit')),
            ],
        ),
        migrations.CreateModel(
            name='MCQresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill1', models.CharField(max_length=50, null=True)),
                ('Skill2', models.CharField(max_length=50, null=True)),
                ('Skill3', models.CharField(max_length=50, null=True)),
                ('Skill4', models.CharField(max_length=50, null=True)),
                ('from_Recruit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Candidate.Recruit')),
            ],
        ),
    ]
