# Generated by Django 3.0.2 on 2020-02-01 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='Resume',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
