# Generated by Django 3.0.2 on 2020-05-07 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0012_delete_application'),
        ('quiz', '0002_auto_20200507_1022'),
        ('Candidate', '0002_auto_20200201_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.PositiveIntegerField(null=True)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.PositiveIntegerField(null=True)),
                ('Marketing', models.PositiveIntegerField(null=True)),
                ('Total', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobenquiryC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('At', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDomainMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='AttemptMarket',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruit',
            name='AttemptTech',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruit',
            name='MarketRating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='recruit',
            name='TechRating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='MCQresult',
        ),
        migrations.AddField(
            model_name='subdomainmark',
            name='Recruit3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='Candidate.Recruit'),
        ),
        migrations.AddField(
            model_name='subdomainmark',
            name='SubDomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
        ),
        migrations.AddField(
            model_name='jobenquiryc',
            name='Recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.Recruit'),
        ),
        migrations.AddField(
            model_name='jobenquiryc',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Jobs'),
        ),
        migrations.AddField(
            model_name='generalmark',
            name='Recruit1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_view', to='Candidate.Recruit'),
        ),
        migrations.AddField(
            model_name='domainmark',
            name='Recruit2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='Candidate.Recruit'),
        ),
    ]
