# Generated by Django 3.0.2 on 2020-03-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0012_delete_application'),
        ('Candidate', '0002_auto_20200201_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobenquiryC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('At', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.TextField()),
                ('Recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.Recruit')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Jobs')),
            ],
        ),
    ]
