# Generated by Django 3.0.2 on 2020-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0003_auto_20200507_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='AttemptMarket',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='AttemptTech',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
