# Generated by Django 3.0.2 on 2020-05-06 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0003_jobenquiryc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='Rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
