# Generated by Django 3.0.2 on 2020-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0004_recruit_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='No_of',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
