# Generated by Django 3.0.2 on 2020-05-06 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0006_auto_20200506_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='No_of',
            new_name='AttemptMarket',
        ),
        migrations.RenameField(
            model_name='recruit',
            old_name='Rating',
            new_name='MarketRating',
        ),
        migrations.AddField(
            model_name='recruit',
            name='AttemptTech',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recruit',
            name='TechRating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
