# Generated by Django 3.0.2 on 2020-06-03 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0006_auto_20200603_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulllistMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roundone', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10)])),
                ('RoundTwo1', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10)])),
                ('RoundTwo2', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10)])),
                ('RoundThree1', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10)])),
                ('RoundThree2', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(10)])),
                ('Recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.Recruit')),
            ],
        ),
    ]
