# Generated by Django 3.0.2 on 2020-05-06 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0007_auto_20200506_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='AttemptMarket',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='AttemptTech',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='MarketRating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='TechRating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
