# Generated by Django 3.0.2 on 2020-06-03 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0007_fulllistmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulllistmarks',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 3, 10, 48, 3, 626645, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
