# Generated by Django 3.0.2 on 2020-06-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0008_fulllistmarks_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Socialmedia', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='Time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='Socialmedia',
            field=models.ManyToManyField(to='Candidate.SocialMedia'),
        ),
    ]
