# Generated by Django 3.0.2 on 2020-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0009_auto_20200628_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='Socialmedia',
            field=models.ManyToManyField(blank=True, to='Candidate.SocialMedia'),
        ),
    ]
