# Generated by Django 3.0.2 on 2020-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0012_recruit_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='SocialMediaTags',
            field=models.ManyToManyField(blank=True, to='Candidate.SocialMediaTags'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='SocioeconomicTags',
            field=models.ManyToManyField(blank=True, to='Candidate.SocioeconomicTags'),
        ),
    ]
