# Generated by Django 3.0.2 on 2020-06-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0013_auto_20200629_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='Residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidate.Residence'),
        ),
    ]
