# Generated by Django 3.0.2 on 2020-07-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0015_auto_20200629_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='SocialMediaTags',
        ),
        migrations.AddField(
            model_name='recruit',
            name='SocialMediaTags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidate.SocialMediaTags'),
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='SocioeconomicTags',
        ),
        migrations.AddField(
            model_name='recruit',
            name='SocioeconomicTags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidate.SocioeconomicTags'),
        ),
    ]
