# Generated by Django 3.0.2 on 2020-07-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0016_auto_20200708_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='SocialMediaTags',
        ),
        migrations.AddField(
            model_name='recruit',
            name='SocialMediaTags',
            field=models.ManyToManyField(blank=True, to='Candidate.SocialMediaTags'),
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='SocioeconomicTags',
        ),
        migrations.AddField(
            model_name='recruit',
            name='SocioeconomicTags',
            field=models.ManyToManyField(blank=True, to='Candidate.SocioeconomicTags'),
        ),
    ]
