# Generated by Django 3.0.2 on 2020-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0017_auto_20200708_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Fi', models.FileField(upload_to='certificate/')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='Bio',
            field=models.TextField(default='zzz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruit',
            name='Experience',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
