# Generated by Django 3.0.2 on 2020-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0019_certificate_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='Skills',
            field=models.ManyToManyField(blank=True, to='Candidate.Skills'),
        ),
    ]
