# Generated by Django 3.0.2 on 2020-07-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0020_recruit_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Fi',
            new_name='File',
        ),
    ]
