# Generated by Django 3.0.2 on 2020-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0021_auto_20200713_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
