# Generated by Django 3.0.2 on 2020-07-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0022_auto_20200716_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobenquiryc',
            name='Skills',
            field=models.ManyToManyField(blank=True, to='Candidate.Skills'),
        ),
    ]
