# Generated by Django 3.0.2 on 2020-08-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0024_jobenquiryc_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
