# Generated by Django 3.0.2 on 2020-02-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('Job_Descreption', models.TextField()),
                ('Level', models.IntegerField()),
                ('Minimum_experience', models.IntegerField()),
                ('prefered_city', models.CharField(max_length=50)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Company')),
            ],
        ),
    ]
