# Generated by Django 3.0.2 on 2020-02-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='fields',
            field=models.CharField(default='tech', max_length=50),
            preserve_default=False,
        ),
    ]
