# Generated by Django 3.0.2 on 2020-02-03 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organization', '0004_auto_20200203_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField()),
                ('at', models.DateTimeField()),
                ('by_recruit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('by_whom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organization.Jobs')),
            ],
        ),
    ]
