# Generated by Django 3.0.2 on 2020-02-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('Organization', '0006_auto_20200203_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Domain'),
        ),
    ]
