# Generated by Django 3.0.2 on 2020-03-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0002_auto_20200201_1710'),
        ('Organization', '0007_auto_20200207_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='by_recruit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Candidate.Recruit'),
        ),
    ]
