# Generated by Django 3.0.2 on 2020-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0008_auto_20200308_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
