# Generated by Django 3.0.2 on 2020-03-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0002_auto_20200201_1710'),
        ('Organization', '0009_auto_20200309_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='by_recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.Recruit'),
        ),
        migrations.AlterField(
            model_name='application',
            name='by_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Jobs'),
        ),
    ]
