# Generated by Django 3.0.2 on 2020-03-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0010_auto_20200309_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='by_whom',
            new_name='job',
        ),
    ]
