# Generated by Django 3.0.2 on 2020-03-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0011_auto_20200309_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
