# Generated by Django 3.0.2 on 2020-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200507_1140'),
        ('Organization', '0012_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='SubDomain',
            field=models.ManyToManyField(to='quiz.SubDomain'),
        ),
    ]
