# Generated by Django 3.0.2 on 2020-07-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_domainquestion_level3'),
        ('Organization', '0015_auto_20200728_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='SubDomain',
        ),
        migrations.AddField(
            model_name='jobs',
            name='SubDomain',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quiz.SubDomain'),
            preserve_default=False,
        ),
    ]
